theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: L'alternative
description: L'Alternative au vote pour les présidentielles de 2022 et 2027
show_downloads: false
